# Generated by Django 2.1 on 2020-02-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JAN',
            fields=[
                ('Total_Order', models.IntegerField(primary_key=True, serialize=False)),
                ('priority_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('Manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Manager_Name', models.CharField(max_length=50)),
                ('Manager_mail', models.CharField(max_length=50)),
                ('Manager_pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
