# Generated by Django 2.1 on 2020-02-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_Name', models.CharField(max_length=50)),
                ('EmpID', models.IntegerField(primary_key=True, serialize=False)),
                ('MarriedID', models.IntegerField()),
                ('MaritalStatusID', models.IntegerField()),
                ('GenderID', models.IntegerField()),
                ('DeptID', models.IntegerField()),
                ('State', models.CharField(max_length=50)),
                ('Zip', models.IntegerField()),
                ('DOB', models.CharField(max_length=50)),
                ('Sex', models.CharField(max_length=50)),
                ('MaritalDesc', models.CharField(max_length=50)),
                ('CitizenDesc', models.CharField(max_length=50)),
            ],
        ),
    ]
