# Generated by Django 2.1 on 2020-02-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coatsapp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('Machine', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('OEF', models.CharField(max_length=50)),
                ('Work_Time', models.CharField(max_length=50)),
                ('Stop_Time', models.CharField(max_length=50)),
                ('Change_batch', models.IntegerField()),
                ('Production_real', models.CharField(max_length=50)),
                ('Production_Real_per_h', models.CharField(max_length=50)),
                ('Doffing_number', models.IntegerField()),
                ('Doffing_avg_time', models.CharField(max_length=50)),
                ('Ongoing_br', models.IntegerField()),
                ('On_going_sph', models.FloatField()),
                ('Low_twist_alarms', models.IntegerField()),
                ('UKG', models.FloatField()),
                ('EmpID', models.IntegerField()),
            ],
        ),
    ]
