# Generated by Django 2.1 on 2020-02-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coatsapp', '0003_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFinish',
            fields=[
                ('Material', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Release', models.DateTimeField(auto_now_add=True)),
                ('wpcnfdate', models.DateTimeField(auto_now_add=True)),
                ('wpcnftime', models.DateTimeField(auto_now_add=True)),
                ('Actual_end', models.DateTimeField(auto_now_add=True)),
                ('Act_finish', models.DateTimeField(auto_now_add=True)),
                ('Target_qty', models.FloatField()),
                ('Del_qty', models.IntegerField()),
                ('Rel_to_Fin', models.FloatField()),
                ('QLead', models.FloatField()),
                ('wp_h', models.FloatField()),
                ('Department_fault', models.CharField(max_length=50)),
            ],
        ),
    ]
