# Generated by Django 2.1 on 2020-02-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coatsapp', '0004_materialfinish'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict_Machine',
            fields=[
                ('machine', models.IntegerField(primary_key=True, serialize=False)),
                ('totallots', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
