# Generated by Django 2.1 on 2020-02-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coatsapp', '0005_predict_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='packing',
            fields=[
                ('packing_consumption', models.IntegerField(primary_key=True, serialize=False)),
                ('packing_needed', models.IntegerField()),
                ('Month', models.IntegerField()),
            ],
        ),
    ]
