# Generated by Django 2.1 on 2020-02-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coatsapp', '0006_packing'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_order',
            fields=[
                ('ORDER_NUMBER', models.IntegerField(primary_key=True, serialize=False)),
                ('ORDER_STARTED', models.CharField(max_length=50)),
                ('ORDER_COMPLETED', models.CharField(max_length=50)),
            ],
        ),
    ]
